export const VIEW_APPFOOTER='VIEW_APPFOOTER';
export const VIEW_LOADING='VIEW_LOADING';
export const UPDATE_DETAIL='UPDATE_DETAIL';
export const CHECK_USER='CHECK_USER';
export const UPDATE_HOME='UPDATE_HOME'; 
export const UPDATE_LIST='UPDATE_LIST'; 