export const VIEW_APPFOOTER='VIEW_APPFOOTER';
export const VIEW_LOADING='VIEW_LOADING';
export const UPDATE_DETAIL='UPDATE_DETAIL';
export const CHECK_USER='CHECK_USER';
export const UPDATE_HOME='UPDATE_HOME'; 
export const UPDATE_LIST='UPDATE_LIST'; 
export const ADD_ITEM = 'ADD_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const REMOVE_ALL = 'REMOVE_ALL';
export const ADD_NUMBER = 'ADD_NUMBER'
export const RED_NUMBER = 'RED_NUMBER'
